spring:
  application:
    name: ms-customer
  config:
    import: optional:configserver:http://localhost:8888 #ruta y puerto del micro config server
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false