server:
  port: 8761 #puerto por defecto de eureka

spring:
  application:
    name: ms-eureka #nombre del micro de eureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #eureka no debe registrarse dentro de si mismo
    fetch-registry: false #eureka no debe registrarse dentro de si mismo
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/